export const GET_SHEET = "GET_SHEET";
export const GET_SHEET_SUCCESS = "GET_SHEET_SUCCESS";
export const GET_SHEET_FAIL = "GET_SHEET_FAIL";

export const SAVE_SHEET = "SAVE_SHEET";
export const SAVE_SHEET_SUCCESS = "SAVE_SHEET_SUCCESS";
export const SAVE_SHEET_FAIL = "SAVE_SHEET_FAIL";

export const CLEAR_SHEET = "CLEAR_SHEET";

export const DELETE_SHEET = "DELETE_SHEET";
export const DELETE_SHEET_SUCCESS = "DELETE_SHEET_SUCCESS";
export const DELETE_SHEET_FAIL = "DELETE_SHEET_FAIL";

export const CLEAR_FAIL = "CLEAR_FAIL";


export const CELL_CURRENT = "CELL_CURRENT";
export const CELL_SELECTED = "CELL_SELECTED";
export const CELL_CLEAR = "CELL_CLEAR";